### ISSUE TITLE
seems very useful cannot run it

### ISSUE THREAD

**Issue by mihai-satmarean** [mattkeeler/ansible-dns-inventory#1]
Hi,
this seems very useful, unfortunatelly I cannot run it, Tried on a MAC OS 

`   import dns.resolver
ImportError: No module named resolver
`

`
pip show dnspython
Name: dnspython
Version: 1.15.0
Summary: DNS toolkit
Home-page: http://www.dnspython.org
Author: Bob Halley
Author-email: halley@dnspython.org
License: BSD-like
Location: /usr/local/lib/python2.7/site-packages
Requires:
`

and on a CentOS 7.1

`
Installed /usr/lib/python2.7/site-packages/dnspython-1.16.0-py2.7.egg

python dns.py
Traceback (most recent call last):
  File "dns.py", line 41, in <module>
    import dns.resolver
  File "/root/ansible-dns-inventory/dns.py", line 41, in <module>
    import dns.resolver
ImportError: No module named resolver
`
Any hint on how to load the library?
Thanks!

**Comment by mattkeeler** [comment]
It looks like the script is trying to import resolver from itself, since it's named the same as the dnspython library package. Rename dns.py to dns_inventory.py and try executing again.

**Comment by mihai-satmarean** [comment]
Thank you,
it did run.
But no result.
I mean result was empty.
Is it possible that we don't have the TXT records?
Thanks!

2017-08-24 17:02 GMT+02:00 Matt Keeler <notifications@github.com>:

**Comment by mattkeeler** [comment]
You'd have to add the TXT records to your zone file in the format specified in the README.

**Comment by mattkeeler** [comment]
The script has been renamed to dns_inventory.py and pushed to master. Closing this issue.

**Comment by luckyelms** [comment]
Hi, very inspiring code though am a bit of new to this & average at coding. Never the less, i ran code on centos 8 and got this error:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dns/resolver.py", line 213, in __init__
    rdclass, rdtype)
  File "/usr/local/lib/python3.6/site-packages/dns/message.py", line 341, in find_rrset
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dns/resolver.py", line 223, in __init__
    dns.rdatatype.CNAME)
  File "/usr/local/lib/python3.6/site-packages/dns/message.py", line 341, in find_rrset
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dns_inventory.py", line 50, in <module>
    records = sorted(dns.resolver.query(domain, 'TXT'), reverse=True)
  File "/usr/local/lib/python3.6/site-packages/dns/resolver.py", line 1102, in query
    lifetime)
  File "/usr/local/lib/python3.6/site-packages/dns/resolver.py", line 1004, in query
    raise_on_no_answer)
  File "/usr/local/lib/python3.6/site-packages/dns/resolver.py", line 232, in __init__
    raise NoAnswer(response=response)
dns.resolver.NoAnswer: The DNS response does not contain an answer to the question: mydomain.com. IN TXT`

Plus, i dont have TXT data, but i would very much want to pull either the PTR hostname (record) or ip address (A records)
